package com.example.collect.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.collect.bean.CartListBean;
import com.example.collect.bean.HistroyBean;

import com.example.collect.db.CartListBeanDao;
import com.example.collect.db.HistroyBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cartListBeanDaoConfig;
    private final DaoConfig histroyBeanDaoConfig;

    private final CartListBeanDao cartListBeanDao;
    private final HistroyBeanDao histroyBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cartListBeanDaoConfig = daoConfigMap.get(CartListBeanDao.class).clone();
        cartListBeanDaoConfig.initIdentityScope(type);

        histroyBeanDaoConfig = daoConfigMap.get(HistroyBeanDao.class).clone();
        histroyBeanDaoConfig.initIdentityScope(type);

        cartListBeanDao = new CartListBeanDao(cartListBeanDaoConfig, this);
        histroyBeanDao = new HistroyBeanDao(histroyBeanDaoConfig, this);

        registerDao(CartListBean.class, cartListBeanDao);
        registerDao(HistroyBean.class, histroyBeanDao);
    }
    
    public void clear() {
        cartListBeanDaoConfig.clearIdentityScope();
        histroyBeanDaoConfig.clearIdentityScope();
    }

    public CartListBeanDao getCartListBeanDao() {
        return cartListBeanDao;
    }

    public HistroyBeanDao getHistroyBeanDao() {
        return histroyBeanDao;
    }

}
