package com.example.collect.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.collect.bean.HistroyBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "HISTROY_BEAN".
*/
public class HistroyBeanDao extends AbstractDao<HistroyBean, String> {

    public static final String TABLENAME = "HISTROY_BEAN";

    /**
     * Properties of entity HistroyBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Keyword = new Property(0, String.class, "keyword", true, "KEYWORD");
        public final static Property Time = new Property(1, long.class, "time", false, "TIME");
    }


    public HistroyBeanDao(DaoConfig config) {
        super(config);
    }
    
    public HistroyBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"HISTROY_BEAN\" (" + //
                "\"KEYWORD\" TEXT PRIMARY KEY NOT NULL ," + // 0: keyword
                "\"TIME\" INTEGER NOT NULL );"); // 1: time
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"HISTROY_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, HistroyBean entity) {
        stmt.clearBindings();
 
        String keyword = entity.getKeyword();
        if (keyword != null) {
            stmt.bindString(1, keyword);
        }
        stmt.bindLong(2, entity.getTime());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, HistroyBean entity) {
        stmt.clearBindings();
 
        String keyword = entity.getKeyword();
        if (keyword != null) {
            stmt.bindString(1, keyword);
        }
        stmt.bindLong(2, entity.getTime());
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public HistroyBean readEntity(Cursor cursor, int offset) {
        HistroyBean entity = new HistroyBean( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // keyword
            cursor.getLong(offset + 1) // time
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, HistroyBean entity, int offset) {
        entity.setKeyword(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setTime(cursor.getLong(offset + 1));
     }
    
    @Override
    protected final String updateKeyAfterInsert(HistroyBean entity, long rowId) {
        return entity.getKeyword();
    }
    
    @Override
    public String getKey(HistroyBean entity) {
        if(entity != null) {
            return entity.getKeyword();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(HistroyBean entity) {
        return entity.getKeyword() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
